# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140609080350) do

  create_table "children", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "last_name"
    t.string   "first_name"
    t.string   "gender"
    t.date     "dob"
    t.integer  "age_years"
    t.integer  "age_months"
    t.integer  "age_total_months"
    t.string   "location"
    t.boolean  "no_parent_present"
    t.boolean  "parental_permission_given"
    t.text     "allergies"
    t.text     "allergies_information"
    t.boolean  "immunization_utd"
    t.boolean  "dtap"
    t.boolean  "hib"
    t.boolean  "pneumovax"
    t.boolean  "hepa"
    t.boolean  "hepb"
    t.boolean  "influenza"
    t.boolean  "mmr"
    t.text     "immunization_needed"
    t.text     "revelant_information"
    t.text     "absences"
    t.integer  "height_feet"
    t.integer  "height_inches"
    t.integer  "height_total_inches"
    t.integer  "height_total_cm"
    t.integer  "weight_lbs"
    t.integer  "weight_oz"
    t.integer  "weight_kg"
    t.integer  "bmi_result"
    t.integer  "bmi_percentile"
    t.integer  "systolic_1"
    t.integer  "diastolic_1"
    t.integer  "systolic_2"
    t.integer  "diastolic_2"
    t.integer  "systolic_3"
    t.integer  "diastolic_3"
    t.integer  "hemoglobin"
    t.integer  "blood_glucose"
  end

  create_table "findings", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "child_id"
    t.string   "well_child_check"
    t.text     "assessment_01"
    t.text     "assessment_02"
    t.text     "assessment_03"
    t.text     "assessment_04"
    t.text     "assessment_05"
    t.text     "assessment_06"
    t.text     "assessment_07"
    t.text     "assessment_08"
    t.text     "assessment_09"
    t.text     "assessment_10"
    t.text     "follow_up_01"
    t.text     "follow_up_02"
    t.text     "follow_up_03"
    t.text     "follow_up_04"
    t.text     "follow_up_05"
    t.text     "follow_up_06"
    t.text     "follow_up_07"
    t.text     "follow_up_08"
    t.text     "follow_up_09"
    t.text     "follow_up_10"
    t.text     "guidance"
    t.string   "chart_complete"
    t.string   "np_signature"
    t.string   "faculty_signature"
    t.string   "other_np_signature"
  end

  create_table "health_records", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "child_id"
    t.integer  "hearing_hz_left_1"
    t.integer  "hearing_db_left_1"
    t.string   "ear_left_pass_1"
    t.integer  "hearing_hz_right_1"
    t.integer  "hearing_db_right_1"
    t.string   "ear_right_pass_1"
    t.integer  "hearing_hz_left_2"
    t.integer  "hearing_db_left_2"
    t.string   "ear_left_pass_2"
    t.integer  "hearing_hz_right_2"
    t.integer  "hearing_db_right_2"
    t.string   "ear_right_pass_2"
    t.integer  "hearing_hz_left_3"
    t.integer  "hearing_db_left_3"
    t.string   "ear_left_pass_3"
    t.integer  "hearing_hz_right_3"
    t.integer  "hearing_db_right_3"
    t.string   "ear_right_pass_3"
    t.text     "hearing_comments"
    t.integer  "vision_acuity_left_1"
    t.integer  "vision_acuity_right_1"
    t.integer  "vision_acuity_both_1"
    t.integer  "vision_acuity_right_2"
    t.integer  "vision_acuity_left_2"
    t.integer  "vision_acuity_both_2"
    t.integer  "vision_acuity_right_3"
    t.integer  "vision_acuity_left_3"
    t.integer  "vision_acuity_both_3"
    t.string   "vision_color_blindness"
    t.string   "cover_test_left"
    t.string   "cover_test_right"
    t.string   "cover_test_both"
    t.string   "wears_corrective_lenses"
    t.text     "vision_comments"
  end

  create_table "physical_exams", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "child_id"
    t.string   "general_appearance"
    t.text     "general_appearance_c"
    t.string   "head"
    t.text     "head_c"
    t.string   "skin"
    t.text     "skin_c"
    t.string   "eyes"
    t.text     "eyes_c"
    t.string   "ears"
    t.text     "ears_c"
    t.string   "nose"
    t.text     "nose_c"
    t.string   "mouth"
    t.text     "mouth_c"
    t.string   "throat"
    t.text     "throat_c"
    t.string   "thyroid"
    t.text     "thyroid_c"
    t.string   "lymph_all_normal"
    t.string   "lymph_pre_auricular"
    t.string   "lymph_post_auricular"
    t.string   "lymph_anterior_cervical"
    t.string   "lymph_posterior_cervical"
    t.string   "lymph_occipital"
    t.string   "lymph_axillary"
    t.text     "lymph_c"
    t.string   "vascular"
    t.text     "vascular_c"
    t.string   "heart"
    t.text     "heart_c"
    t.string   "lungs"
    t.text     "lungs_c"
    t.string   "abdomen"
    t.text     "abdomen_c"
    t.string   "musculoskeletal"
    t.text     "musculoskeletal_c"
    t.string   "scoliosis"
    t.text     "scoliosis_c"
    t.string   "neuro"
    t.text     "neuro_c"
  end

  create_table "users", force: true do |t|
    t.string   "user_name"
    t.string   "password"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "password_digest"
    t.string   "remember_token"
    t.string   "role"
  end

  add_index "users", ["remember_token"], name: "index_users_on_remember_token"
  add_index "users", ["user_name"], name: "index_users_on_user_name", unique: true

end
