class RemoveNameFromChildren < ActiveRecord::Migration
  def change
    remove_column :children, :name, :string
    remove_column :children, :gender
		remove_column :children, :no_parent_present
		remove_column :children, :parental_permission_given
    remove_column :children, :allergies
    remove_column :children, :allergies_info
    remove_column :children, :immunization_review
    remove_column :children, :relevant_information
    remove_column :children, :location
    remove_column :children, :age_years
    remove_column :children, :age_total_months
    remove_column :children, :immunization_utd
    remove_column :children, :dtap
    remove_column :children, :hib
    remove_column :children, :pneumovax
    remove_column :children, :hepa
    remove_column :children, :influenza
    remove_column :children, :mmr
    remove_column :children, :dob
    remove_column :children, :age_months
    remove_column :findings, :diagnosis_treatment
    remove_column :findings, :faculty_signature
    remove_column :findings, :faculty_sig_date
    remove_column :findings, :child_id
    remove_column :findings, :general_statement
    remove_column :findings, :signature
    remove_column :findings, :sig_date
    remove_column :findings, :finding_a
    remove_column :findings, :finding_b
    remove_column :findings, :finding_c
    remove_column :findings, :finding_d
    remove_column :findings, :treatment_a
    remove_column :findings, :treatment_b
    remove_column :findings, :treatment_c
    remove_column :findings, :treatment_d
    remove_column :health_records, :relevant_information
    remove_column :health_records, :blood_pressure
    remove_column :health_records, :hemoglobin
    remove_column :health_records, :hearing_test
    remove_column :health_records, :hearing_rescreening
    remove_column :health_records, :hearing_comments
    remove_column :health_records, :vision_test
    remove_column :health_records, :vision_rescreening
    remove_column :health_records, :vision_color
    remove_column :health_records, :vision_comments
    remove_column :health_records, :hearing_result_right_2
    remove_column :health_records, :hearing_result_left_3
    remove_column :health_records, :hearing_result_right_3
    remove_column :health_records, :hearing_result_left_2
    remove_column :health_records, :well_child_exam
    remove_column :health_records, :no_parent
    remove_column :health_records, :systolic1
    remove_column :health_records, :diastolic1
    remove_column :health_records, :systolic2
    remove_column :health_records, :diastolic2
    remove_column :health_records, :systolic3
    remove_column :health_records, :diastolic3
    remove_column :health_records, :blood_sugar
    remove_column :health_records, :vision_acuity_right_2
    remove_column :health_records, :vision_acuity_left_2
    remove_column :health_records, :vision_acuity_both_2
    remove_column :health_records, :vision_acuity_right_3
    remove_column :health_records, :vision_acuity_left_3
    remove_column :health_records, :vision_acuity_both_3
    remove_column :health_records, :too_young
    remove_column :health_records, :too_young_bloodsugar
    remove_column :health_records, :too_young_hemoglobin
    remove_column :health_records, :too_young_audiometry
    remove_column :health_records, :too_young_vision
    remove_column :health_records, :child_id
    remove_column :health_records, :height_feet
    remove_column :health_records, :height_inches
    remove_column :health_records, :height_total_inches
    remove_column :health_records, :height_total_cm
    remove_column :health_records, :weight_lbs
    remove_column :health_records, :weight_oz
    remove_column :health_records, :bmi_result
    remove_column :health_records, :blood_glucose
    remove_column :health_records, :hearing_result_left_1
    remove_column :health_records, :hearing_result_right_1
    remove_column :health_records, :ear_form_decibel_test_1
    remove_column :health_records, :ear_form_decibel_test_2
    remove_column :health_records, :ear_form_decibel_test_3
    remove_column :health_records, :vision_acuity_left_1
    remove_column :health_records, :vision_acuity_right_1
    remove_column :health_records, :vision_acuity_both_1
    remove_column :health_records, :wears_corrective_lenses
    remove_column :physical_exams, :general_appearance
    remove_column :physical_exams, :general_appearance_c
    remove_column :physical_exams, :posture
    remove_column :physical_exams, :posture_c
    remove_column :physical_exams, :speech
    remove_column :physical_exams, :speech_c
    remove_column :physical_exams, :head
    remove_column :physical_exams, :head_c
    remove_column :physical_exams, :skin
    remove_column :physical_exams, :skin_c
    remove_column :physical_exams, :eyes_external_aspects
    remove_column :physical_exams, :eyes_external_aspects_c
    remove_column :physical_exams, :eyes_optic_fundiscopic
    remove_column :physical_exams, :eyes_optic_fundiscopic_c
    remove_column :physical_exams, :eyes_cover_test
    remove_column :physical_exams, :eyes_cover_test_c
    remove_column :physical_exams, :ears_external
    remove_column :physical_exams, :ears_external_c
    remove_column :physical_exams, :ears_tympanic
    remove_column :physical_exams, :ears_tympanic_c
    remove_column :physical_exams, :nose
    remove_column :physical_exams, :nose_c
    remove_column :physical_exams, :teeth
    remove_column :physical_exams, :teeth_c
    remove_column :physical_exams, :heart
    remove_column :physical_exams, :heart_c
    remove_column :physical_exams, :lungs
    remove_column :physical_exams, :lungs_c
    remove_column :physical_exams, :abdomen
    remove_column :physical_exams, :abdomen_c
    remove_column :physical_exams, :bones
    remove_column :physical_exams, :bones_c
    remove_column :physical_exams, :scoliosis_gross_motor
    remove_column :physical_exams, :scoliosis_gross_motor_c
    remove_column :physical_exams, :scoliosis_fine_motor
    remove_column :physical_exams, :scoliosis_fine_motor_c
    remove_column :physical_exams, :scoliosis_comm_skill
    remove_column :physical_exams, :scoliosis_comm_skill_c
    remove_column :physical_exams, :scoliosis_cognitive
    remove_column :physical_exams, :scoliosis_cognitive_c
    remove_column :physical_exams, :scoliosis_self_help
    remove_column :physical_exams, :scoliosis_self_help_c
    remove_column :physical_exams, :scoliosis_social_skills
    remove_column :physical_exams, :scoliosis_social_skills_c
    remove_column :physical_exams, :glandis
    remove_column :physical_exams, :glandis_c
    remove_column :physical_exams, :muscular_coord
    remove_column :physical_exams, :muscular_coord_c
    remove_column :physical_exams, :other
    remove_column :physical_exams, :other_c
    remove_column :physical_exams, :child_id
  end
end
