class AddLastNameToChildren < ActiveRecord::Migration
  def change
    add_column :children, :last_name, :string
		add_column :children, :first_name, :string
		add_column :children, :gender, :string
  	add_column :children, :dob, :date
  	add_column :children, :age_years, :integer
  	add_column :children, :age_months, :integer
  	add_column :children, :age_total_months, :integer
  	add_column :children, :location, :string
  	add_column :children, :no_parent_present, :boolean
  	add_column :children, :parental_permission_given, :boolean
  	add_column :children, :allergies, :text
  	add_column :children, :allergies_information, :text
  	add_column :children, :immunization_utd, :boolean
  	add_column :children, :dtap, :boolean
  	add_column :children, :hib, :boolean
  	add_column :children, :pneumovax, :boolean
  	add_column :children, :hepa, :boolean
  	add_column :children, :hepb, :boolean
  	add_column :children, :influenza, :boolean
  	add_column :children, :mmr, :boolean
  	add_column :children, :immunization_needed, :text
  	add_column :children, :revelant_information, :text
  	add_column :children, :absences, :text
		add_column :children, :height_feet, :integer
		add_column :children, :height_inches, :integer
		add_column :children, :height_total_inches, :integer
		add_column :children, :height_total_cm, :integer
		add_column :children, :weight_lbs, :integer
		add_column :children, :weight_oz, :integer
		add_column :children, :weight_kg, :integer
		add_column :children, :bmi_result, :integer
		add_column :children, :bmi_percentile, :integer
		add_column :children, :systolic_1, :integer
		add_column :children, :diastolic_1, :integer
		add_column :children, :systolic_2, :integer
		add_column :children, :diastolic_2, :integer
		add_column :children, :systolic_3, :integer
		add_column :children, :diastolic_3, :integer
		add_column :children, :hemoglobin, :integer
		add_column :children, :blood_glucose, :integer
		add_column :health_records, :child_id, :integer
		add_column :health_records, :hearing_hz_left_1, :integer
		add_column :health_records, :hearing_db_left_1, :integer
		add_column :health_records, :ear_left_pass_1, :string
		add_column :health_records, :hearing_hz_right_1, :integer
		add_column :health_records, :hearing_db_right_1, :integer
		add_column :health_records, :ear_right_pass_1, :string
		add_column :health_records, :hearing_hz_left_2, :integer
		add_column :health_records, :hearing_db_left_2, :integer
		add_column :health_records, :ear_left_pass_2, :string
		add_column :health_records, :hearing_hz_right_2, :integer
		add_column :health_records, :hearing_db_right_2, :integer
		add_column :health_records, :ear_right_pass_2, :string
		add_column :health_records, :hearing_hz_left_3, :integer
		add_column :health_records, :hearing_db_left_3, :integer
		add_column :health_records, :ear_left_pass_3, :string
		add_column :health_records, :hearing_hz_right_3, :integer
		add_column :health_records, :hearing_db_right_3, :integer
		add_column :health_records, :ear_right_pass_3, :string
		add_column :health_records, :hearing_comments, :text
		add_column :health_records, :vision_acuity_left_1, :integer
		add_column :health_records, :vision_acuity_right_1, :integer
		add_column :health_records, :vision_acuity_both_1, :integer
		add_column :health_records, :vision_acuity_right_2, :integer
		add_column :health_records, :vision_acuity_left_2, :integer
		add_column :health_records, :vision_acuity_both_2, :integer
		add_column :health_records, :vision_acuity_right_3, :integer
		add_column :health_records, :vision_acuity_left_3, :integer
		add_column :health_records, :vision_acuity_both_3, :integer
		add_column :health_records, :vision_color_blindness, :string
		add_column :health_records, :cover_test_left, :string
		add_column :health_records, :cover_test_right, :string
		add_column :health_records, :cover_test_both, :string
		add_column :health_records, :wears_corrective_lenses, :string
		add_column :health_records, :vision_comments, :text
		add_column :physical_exams, :child_id, :integer
		add_column :physical_exams, :general_appearance, :string
		add_column :physical_exams, :general_appearance_c, :text
		add_column :physical_exams, :head, :string
		add_column :physical_exams, :head_c, :text
		add_column :physical_exams, :skin, :string
		add_column :physical_exams, :skin_c, :text
		add_column :physical_exams, :eyes, :string
		add_column :physical_exams, :eyes_c, :text
		add_column :physical_exams, :ears, :string
		add_column :physical_exams, :ears_c, :text
		add_column :physical_exams, :nose, :string
		add_column :physical_exams, :nose_c, :text
		add_column :physical_exams, :mouth, :string
		add_column :physical_exams, :mouth_c, :text
		add_column :physical_exams, :throat, :string
		add_column :physical_exams, :throat_c, :text
		add_column :physical_exams, :thyroid, :string
		add_column :physical_exams, :thyroid_c, :text
		add_column :physical_exams, :lymph_all_normal, :string
		add_column :physical_exams, :lymph_pre_auricular, :string
		add_column :physical_exams, :lymph_post_auricular, :string
		add_column :physical_exams, :lymph_anterior_cervical, :string
		add_column :physical_exams, :lymph_posterior_cervical, :string
		add_column :physical_exams, :lymph_occipital, :string
		add_column :physical_exams, :lymph_axillary, :string
		add_column :physical_exams, :lymph_c, :text
		add_column :physical_exams, :vascular, :string
		add_column :physical_exams, :vascular_c, :text
		add_column :physical_exams, :heart, :string
		add_column :physical_exams, :heart_c, :text
		add_column :physical_exams, :lungs, :string
		add_column :physical_exams, :lungs_c, :text
		add_column :physical_exams, :abdomen, :string
		add_column :physical_exams, :abdomen_c, :text
		add_column :physical_exams, :musculoskeletal, :string
		add_column :physical_exams, :musculoskeletal_c, :text
		add_column :physical_exams, :scoliosis, :string
		add_column :physical_exams, :scoliosis_c, :text
		add_column :physical_exams, :neuro, :string
		add_column :physical_exams, :neuro_c, :text
		add_column :findings, :child_id, :integer
		add_column :findings, :well_child_check, :string
		add_column :findings, :findings_01, :text
		add_column :findings, :findings_02, :text
		add_column :findings, :findings_03, :text
		add_column :findings, :findings_04, :text
		add_column :findings, :findings_05, :text
		add_column :findings, :findings_06, :text
		add_column :findings, :findings_07, :text
		add_column :findings, :findings_08, :text
		add_column :findings, :findings_09, :text
		add_column :findings, :findings_10, :text
		add_column :findings, :follow_up_01, :text
		add_column :findings, :follow_up_02, :text
		add_column :findings, :follow_up_03, :text
		add_column :findings, :follow_up_04, :text
		add_column :findings, :follow_up_05, :text
		add_column :findings, :follow_up_06, :text
		add_column :findings, :follow_up_07, :text
		add_column :findings, :follow_up_08, :text
		add_column :findings, :follow_up_09, :text
		add_column :findings, :follow_up_10, :text
		add_column :findings, :guidance, :text
		add_column :findings, :chart_complete, :string
		add_column :findings, :np_signature, :string
		add_column :findings, :faculty_signature, :string
		add_column :findings, :other_np_signature, :string
  end
end
