class AddHearingHzLeft1ToChildren < ActiveRecord::Migration
  def change
    add_column :children, :hearing_hz_left_1, :interger
    add_column :children, :hearing_db_left_1, :integer
		add_column :children, :ear_left_pass_1, :string
		add_column :children, :hearing_hz_right_1, :integer
		add_column :children, :hearing_db_right_1, :integer
		add_column :children, :ear_right_pass_1, :string
		add_column :children, :hearing_hz_left_2, :integer
		add_column :children, :hearing_db_left_2, :integer
		add_column :children, :ear_left_pass_2, :string
		add_column :children, :hearing_hz_right_2, :integer
		add_column :children, :hearing_db_right_2, :integer
		add_column :children, :ear_right_pass_2, :string
		add_column :children, :hearing_hz_left_3, :integer
		add_column :children, :hearing_db_left_3, :integer
		add_column :children, :ear_left_pass_3, :string
		add_column :children, :hearing_hz_right_3, :integer
		add_column :children, :hearing_db_right_3, :integer
		add_column :children, :ear_right_pass_3, :string
		add_column :children, :hearing_comments, :text
		add_column :children, :vision_acuity_left_1, :integer
		add_column :children, :vision_acuity_right_1, :integer
		add_column :children, :vision_acuity_both_1, :integer
		add_column :children, :vision_acuity_right_2, :integer
		add_column :children, :vision_acuity_left_2, :integer
		add_column :children, :vision_acuity_both_2, :integer
		add_column :children, :vision_acuity_right_3, :integer
		add_column :children, :vision_acuity_left_3, :integer
		add_column :children, :vision_acuity_both_3, :integer
		add_column :children, :vision_color_blindness, :string
		add_column :children, :cover_test_left, :string
		add_column :children, :cover_test_right, :string
		add_column :children, :cover_test_both, :string
		add_column :children, :wears_corrective_lenses, :string
		add_column :children, :vision_comments, :text
		add_column :children, :general_appearance, :string
		add_column :children, :general_appearance_c, :text
		add_column :children, :head, :string
		add_column :children, :head_c, :text
		add_column :children, :skin, :string
		add_column :children, :skin_c, :text
		add_column :children, :eyes, :string
		add_column :children, :eyes_c, :text
		add_column :children, :ears, :string
		add_column :children, :ears_c, :text
		add_column :children, :nose, :string
		add_column :children, :nose_c, :text
		add_column :children, :mouth, :string
		add_column :children, :mouth_c, :text
		add_column :children, :throat, :string
		add_column :children, :throat_c, :text
		add_column :children, :thyroid, :string
		add_column :children, :thyroid_c, :text
		add_column :children, :lymph_all_normal, :string
		add_column :children, :lymph_pre_auricular, :string
		add_column :children, :lymph_post_auricular, :string
		add_column :children, :lymph_anterior_cervical, :string
		add_column :children, :lymph_posterior_cervical, :string
		add_column :children, :lymph_occipital, :string
		add_column :children, :lymph_axillary, :string
		add_column :children, :lymph_c, :text
		add_column :children, :vascular, :string
		add_column :children, :vascular_c, :text
		add_column :children, :heart, :string
		add_column :children, :heart_c, :text
		add_column :children, :lungs, :string
		add_column :children, :lungs_c, :text
		add_column :children, :abdomen, :string
		add_column :children, :abdomen_c, :text
		add_column :children, :musculoskeletal, :string
		add_column :children, :musculoskeletal_c, :text
		add_column :children, :scoliosis, :string
		add_column :children, :scoliosis_c, :text
		add_column :children, :neuro, :string
		add_column :children, :neuro_c, :text
		add_column :children, :well_child_check, :string
		add_column :children, :children_01, :text
		add_column :children, :children_02, :text
		add_column :children, :children_03, :text
		add_column :children, :children_04, :text
		add_column :children, :children_05, :text
		add_column :children, :children_06, :text
		add_column :children, :children_07, :text
		add_column :children, :children_08, :text
		add_column :children, :children_09, :text
		add_column :children, :children_10, :text
		add_column :children, :follow_up_01, :text
		add_column :children, :follow_up_02, :text
		add_column :children, :follow_up_03, :text
		add_column :children, :follow_up_04, :text
		add_column :children, :follow_up_05, :text
		add_column :children, :follow_up_06, :text
		add_column :children, :follow_up_07, :text
		add_column :children, :follow_up_08, :text
		add_column :children, :follow_up_09, :text
		add_column :children, :follow_up_10, :text
		add_column :children, :guidance, :text
		add_column :children, :chart_complete, :string
		add_column :children, :np_signature, :string
		add_column :children, :faculty_signature, :string
		add_column :children, :other_np_signature, :string
  end
end
